# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: infra-as-code-codebuild-2
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1
  # iamRoleStatements:
  #   - Effect: "Allow"
  #     Action:
  #      - "secretsmanager:GetSecretValue"
  #     Resource: "arn:aws:secretsmanager:eu-central-1:763455941045:secret:Github-qVbwnY"
custom:
  GitHubAccessToken: ${ssm:/aws/reference/secretsmanager/Github~true}

# you can add CloudFormation resource templates here
resources:
  Resources:
    CodeBuildSourceCredential:
      Type: AWS::CodeBuild::SourceCredential
      Properties:
        Token: ${self:custom.GitHubAccessToken.GithubAccessToken}
        ServerType: GITHUB
        AuthType: PERSONAL_ACCESS_TOKEN
    CodeBuildProject:
      Type: AWS::CodeBuild::Project
      Properties:
        Name: dev-code-build-instance
        Description: this-is-my-description
        ServiceRole: arn:aws:iam::763455941045:role/CodeBuild_Serverless_Admin
        Artifacts:
          Type: NO_ARTIFACTS
        Environment:
          Type: LINUX_CONTAINER
          ComputeType: BUILD_GENERAL1_SMALL
          Image: "aws/codebuild/standard:4.0"
        Source:
          Type: GITHUB
          Location: https://github.com/R0fedex/aws-training-codebuild-demo
        Triggers:
          Webhook: true
          FilterGroups:
            - - Type: EVENT
                Pattern: PUSH
      DependsOn: CodeBuildSourceCredential
