service: MyApp

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1
  # iamRoleStatements:
  #   - Effect: "Allow"
  #     Action:
  #      - "secretsmanager:GetSecretValue"
  #     Resource: "arn:aws:secretsmanager:eu-central-1:763455941045:secret:Github-qVbwnY"
plugins:
  - serverless-offline
  - serverless-stack-output
custom:
  #GitHubAccessToken: ${ssm:/aws/reference/secretsmanager/Github~true} --using AWS Secrets Manager
  #below using AWS Parameter store
  GitHubAccessToken: ${ssm:GithubAccessToken:1~true}
  output:
    file: /build/stackCreationOutput.json

functions:
  randomHello:
    handler: handler.randomHello
    events:
      - http:
          path: randomhello
          method: get

# you can add CloudFormation resource templates here
resources:
  Resources:
    DeploymentArtifactBucket:
      Type: AWS::S3::Bucket
      DeletionPolicy: Delete
      Properties:
        AccessControl: Private
        VersioningConfiguration:
          # The guide recommends Enabled but I can't see why
          Status: Suspended

    CodePipelineProject:
      Type: AWS::CodePipeline::Pipeline
      Properties:
        ArtifactStore:
          Type: S3
          Location: !Ref DeploymentArtifactBucket
        RoleArn: arn:aws:iam::763455941045:role/CodeBuild_Serverless_Admin
        DisableInboundStageTransitions:
          - Reason: Manual approval needed for production deployment
            StageName: ManualApproval
        Stages:
          - Name: Source
            Actions:
              - Name: Get-sources
                ActionTypeId:
                  Category: Source
                  Owner: ThirdParty
                  Provider: GitHub
                  Version: 1
                OutputArtifacts:
                  - Name: MyAppSourceCodeArtifact
                Configuration:
                  Owner: R0fedex
                  Repo: aws-training-codebuild-demo
                  Branch: master
                  #OAuthToken: ${ssm:/aws/reference/secretsmanager/Github~true} --using AWS Secrets Manager
                  OAuthToken: ${ssm:GithubAccessToken~true} #having this in a variable didn't work, but having it inline works?!
                RunOrder: 1 # The order of this action inside this stage
          - Name: Development
            Actions:
              - Name: Deploy-to-Development
                ActionTypeId:
                  Category: Build
                  Owner: AWS
                  Provider: CodeBuild
                  Version: 1
                RunOrder: 1
                Configuration:
                  ProjectName: TestAndDeployToDev
                InputArtifacts:
                  - Name: MyAppSourceCodeArtifact
          - Name: ManualApproval
            Actions:
              - Name: Manual-Approval
                ActionTypeId:
                  Category: Approval
                  Owner: AWS
                  Provider: Manual
                  Version: 1
          - Name: Production
            Actions:
              - Name: Deploy-to-Production
                ActionTypeId:
                  Category: Build
                  Owner: AWS
                  Provider: CodeBuild
                  Version: 1
                RunOrder: 1
                Configuration:
                  ProjectName: DeployToProduction
                InputArtifacts:
                  - Name: MyAppSourceCodeArtifact

    TestAndDeployToDev:
      Type: AWS::CodeBuild::Project
      Properties:
        Name: TestAndDeployToDev
        ServiceRole: arn:aws:iam::763455941045:role/CodeBuild_Serverless_Admin
        Artifacts:
          Type: CODEPIPELINE
        Environment:
          Type: LINUX_CONTAINER
          ComputeType: BUILD_GENERAL1_SMALL
          Image: aws/codebuild/standard:4.0
          EnvironmentVariables:
            - Name: BUILD_ARTIFACT_BUCKET
              Value: !Ref DeploymentArtifactBucket
        Source:
          Type: CODEPIPELINE
          BuildSpec: "buildspecs/buildspec-dev.yaml"
        TimeoutInMinutes: 10

    DeployToProduction:
      Type: AWS::CodeBuild::Project
      Properties:
        Name: DeployToProduction
        ServiceRole: arn:aws:iam::763455941045:role/CodeBuild_Serverless_Admin
        Artifacts:
          Type: CODEPIPELINE
        Environment:
          Type: LINUX_CONTAINER
          ComputeType: BUILD_GENERAL1_SMALL
          Image: aws/codebuild/standard:4.0
          EnvironmentVariables:
            - Name: BUILD_ARTIFACT_BUCKET
              Value: !Ref DeploymentArtifactBucket
        Source:
          Type: CODEPIPELINE
          BuildSpec: "buildspecs/buildspec-prod.yml"
        TimeoutInMinutes: 10
